### ISSUE TITLE
Missing code.

### ISSUE THREAD

**Issue by victorwyee** [flamholz/baywheels-monitor#1]
Saw your opinion piece on Berkeleyside just now. Great analysis, and I was pretty excited to see a repo linked (I think for the first time on Berkeleyside, too). But I think your code might be on another branch or needs to be pushed?

**Comment by flamholz** [comment]
Ah good point. It's on my home comptuer. I thought I had pushed but I will
do so when I get home. I didn't realize they would publish the text without
notifying me first.
A

**Comment by flamholz** [comment]
OK! The code is pushed now.
The raw data files are still on my machine since there are too many of them
to committ, but a parsed csv of the timeseries is zipped in the data/
folder.
Avi
